<?php defined('BASEPATH') or die('Restricted access');?>

<div class="container cause-list">
	<div class="row">
		
		<div class="alert alert-info hidden-print col-md-12">
			<strong>Info!</strong> We recomend print cause list use <strong>Mozila Firefox Browser</strong> and Save print into <strong>Microsoft XPS Document</strong> then Print it!.
		</div>
	
		<div class="panel-body">
				
			<table class="table center bg-white table-bordered table-hover pashi-list" id="" dir="rtl">
				<thead class="urdu">
					<tr>
						<th class="court-name" colspan="10">
							<h2 class="court-title urdu m-b-20"><?php echo $court_by_user->court_name.' '.'<small>'.$court_by_user->desgn_name.'</small>'; ?></h2>
							<h3><span class="urdu">فہرست مقدمات مورخہ</span> <?php echo @date('Y-m-d', @strtotime($doh)); ?><span class="urdu"><?php echo ' '.'بروز'.' '.$day; ?> </span></h3>
						</th>
					</tr>
					<tr>
						<th class="srno">نمبر شمار</th>
						<th><a href="#" data-toggle="tooltip" title="Computer I.D Generated by Software">کمپیوٹر <br />ID</a></th>
						<th class="case_no">نمبر وسال مقدمہ</th>
						<th>نوعیت دعوی، نوعیت فوجداری <br />مقدمہ و نوعیت جرائم</th>
						<th>مدعی/مدعا علیہ<br>مستغیث/ ملزم</th>
						<th>کاروائی امروزہ</th>
						<th>کاروائی آئندہ</th>
						<th>آئندہ تاریخ پیشی</th>
						<th class="actions hidden-print">Actions</th>
						<th class="hidden-print">Cases Detail</th>
					</tr>
				</thead>
				
				<tbody>
				<?php $i=1; ?>
				
				<?php foreach ($stages as $stage) : ?>
					
					<tr>
						<td colspan="10" dir="rtl"><h4 class="urdu"><?php echo $stage->stage_name?></h4></td>
					</tr>
					
					<?php foreach($stage->cases as $case) : ?>
									
					<tr class="text-center">
						<td><?php echo $i++;?></td>
						<td><?php echo $case->case_id; ?></td>
												
						<td class="ltr"><?php if (empty($case->fir_no)) { echo $case->reg_no.'-'.$case->cat_reg_no; } else { echo $case->fir_no.'/' . @date('y', @strtotime($case->fir_date)); } ?></td>
						<td class="td-4"><?php if(!empty($case->ps_name)) { echo '<span class="pull-right ltr">'.substr($case->offence, 0,6).'</span> <span class="urdu pull-left">'.$case->ps_name.'</span>'; } else { echo '<span class="pull-right eng">'.$case->cat_name.'</span> <span class="urdu pull-left">'.$case->cat_nature.'</span>'; }?></td>
						<td class="c-title"><p class="urdu title"><?php echo $case->case_title?></p></td>
	
						<td class="td-6"></td>
						<td class="td-7"></td>
						<td class="td-8"></td>
						
						<td class="action hidden-print">
							<a href="<?php echo base_url('admin/cases/add_ndoh/'.$case->case_id) ?>" target="_blank" class="btn btn-warning btn-xs" data-toggle="tooltip" title="Edit Case"><span class="glyphicon glyphicon-edit"></span> Edit</a>
						</td>
						<td class="hidden-print">
							<a class="btn btn-primary btn-sm" href="<?php echo base_url('admin/cases_list/case_detail/'.$case->case_id); ?>" data-toggle="tooltip" title="Click Here for Compolete Case History" target="_blank">History</a>
						</td>
					</tr>
						
					<?php 
						endforeach; 
				 	endforeach; 
				 ?>
				
				</tbody>
			</table>

		</div>
		
		<div class="center hidden-print">
			<a class="btn btn-primary btn-rounded" onClick="window.print()"><span class="glyphicon glyphicon-print"></span> Print Cause List</a>
		</div>
		
	</div>
</div>
